### ISSUE TITLE
Colvolver and headphone surround sound missing

### ISSUE THREAD

**Issue by rabaimorp** [WSTxda/ViperFX-RE-Releases#10]
My favorite audio mods, colvolver and headphone surround sound are missing

**Comment by Shubhamkr4** [comment]
If you are using re engineered those options are not present yet

**Comment by Shubhamkr4** [comment]
> > If you are using re engineered those options are not present yet
> 
> So you mean they are going to be added?

Yes they will be added in the future updates

**Comment by WSTxda** [comment]
They will be added soon, but perhaps they will come with a new manager application by Iscle

**Comment by ThreeDeeJay** [comment]
Since Convolver's planned for a future update, it might be a good idea to keep at least 1 of these issues open for development notifications, because they're all marked as completed, not planned or duplicate. Also might wanna fix the typo in the title so people can find it more easily.

In the meantime, I'm just glad convolver and all other features in [ViPER4AndroidRepackaged](https://github.com/programminghoch10/ViPER4AndroidRepackaged/releases/latest) still work on Android 16 (LineageOS 23) but it'd still be nice for development to continue somehow. 👀👌
